name: bootstrap_scss_example # change this line to have your library name
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  bootstrap_scss:
    git: https://github.com/Dart-Land/bootstrap_scss.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
  sass_builder: ^2.0.0
