woff2_compress OpenSans-BoldItalic.ttf
woff2_compress OpenSans-Bold.ttf
woff2_compress OpenSans-ExtraBoldItalic.ttf
woff2_compress OpenSans-ExtraBold.ttf
woff2_compress OpenSans-Italic.ttf
woff2_compress OpenSans-LightItalic.ttf
woff2_compress OpenSans-Light.ttf
woff2_compress OpenSans-Regular.ttf
woff2_compress OpenSans-SemiBoldItalic.ttf
woff2_compress OpenSans-SemiBold.ttf
